COMPONENTS := ./Fw

OUTPUTFILE := a4x.rom

MOVEEXPR := text=0xFFFE0000,data=0x1000,bss=data+data_size

INCDIR := ./Include/:../Headers
LIBDIR := ../../newsdk/Rtl/Headers
LIBS := ../../newsdk/Rtl/obj/xr17032/Rtl.lib

MKBINARY := 1

include $(REPO)/Project.mk