COMPONENTS := ./Fw

OUTPUTFILE := a4x.rom

# Make sure to update A4X_DATA_START if you change this.
MOVEEXPR := text=0xFFFE0000,data=0x2000,bss=data+data_size

INCDIR := ./Include/:../Headers

MKBINARY := 1

include $(REPO)/Project.mk